#!/bin/sh
cd 0
rm c* pointLevel 
cd ../constant/polyMesh/
rm -r boundary cell* face* neighbour owner pointLevel point* refinementHistory sets surfaceIndex 
cd ../../
blockMesh
snappyHexMesh -overwrite


# ----------------------------------------------------------------- end-of-file
